{
 "title": "Service Level Summary",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "query": "SELECT DISTINCT environment FROM suite_results"
   },
   {
    "name": "Service",
    "query": "SELECT DISTINCT service FROM suite_results"
   },
   {
    "name": "TestType",
    "query": "SELECT DISTINCT test_type FROM suite_results"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level Tests - ${Service}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Service",
   "targets": [
    {}
   ]
  },
  {
   "title": "$TestType tests builds - $Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT  $__timeGroupAlias(created_at,$__interval,0),  avg(total_skipped) AS \"skipped\",  avg(total_failed) AS \"failed\",  avg(total_passed) AS \"passed\" FROM suite_results WHERE  service = $Service AND test_type = $TestType GROUP BY 1, build ORDER BY 1"
    }
   ]
  },
  {
   "title": "$TestType test coverage - $Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n coverage FROM suite_results WHERE service = $Service ORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(build) FROM suite_results WHERE service = $Service "
    }
   ]
  },
  {
   "title": "No of Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "Select total_executed from suite_results WHERE service = $Service ORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Successful Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(build) FROM suite_results WHERE total_failed=0 AND total_skipped=0 AND service = $Service "
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(build) \nFROM suite_results \nWHERE (total_failed > 0 OR total_skipped > 0)\nAND service = 'backend';"
    }
   ]
  }
 ]
}